name: dsci511
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - pip
  - beautifulsoup4
  - pip:
      - nbstripout
      - osmnx
      - geopandas
      - geojson
